[package]
name = "dj"
authors = ["Vlad Barmichev <barmichev@gmail.com"]
description = "Console launcher for Django applications."
version = "0.1.0"
edition = "2024"
rust-version = "1.93"

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"

[dependencies]
anyhow = "1"
argh = "0.1"
dotenvy = "0.15"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.39"
toml = "1.1.4"

[lints.rust]
deprecated = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
nonstandard_style = { level = "warn", priority = -1 }
redundant_lifetimes = "warn"
unreachable_pub = "warn"
unsafe_code = "warn"
unused_crate_dependencies = "warn"
unused_must_use = "warn"
