[package]
name = "dj"
authors = ["Vlad Barmichev <barmichev@gmail.com"]
description = "Console launcher for Django applications."
version = "0.1.2"
edition = "2024"
rust-version = "1.93"

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"

[dependencies]
anyhow = "1"
clap = {version = "4", features = ["derive"]}
dotenvy = "0.15"
log = { version = "0" }
env_logger = { version = "0" }
regex = "1"
serde = { version = "1", features = ["derive"] }
toml = "1"

[lints.rust]
deprecated = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
nonstandard_style = { level = "warn", priority = -1 }
redundant_lifetimes = "warn"
unreachable_pub = "warn"
unsafe_code = "warn"
unused_crate_dependencies = "warn"
unused_must_use = "warn"
